// Generated by IP Generator (Version 2016.4A build 15480)



module pll_125 (
    
    pll_lock,
    
    clkout_0,
    
    clkin1
);


localparam CLKIN_FREQ = "50MHz"; //@IPC float 20.0,600.0

localparam DYNAMIC_CLKIN_EN = "FALSE"; //@IPC bool

localparam CLKIN_SSEL       = 0;           

localparam DYNAMIC_IDIV_EN = "FALSE"; //@IPC bool

localparam STATIC_IDIV = 2; //@IPC int 1,64

localparam DYNAMIC_FDIV_EN = "FALSE"; //@IPC bool

localparam STATIC_FDIV = 5; //@IPC int 1,64

localparam DYNAMIC_ODIV_EN = "FALSE"; //@IPC bool

localparam STATIC_ODIV = 8; //@IPC int 2,128

localparam CLKO2_SEL = 1; //@IPC enum 0,1,2

localparam DYNAMIC_O2DIV_EN = "FALSE"; //@IPC bool

localparam STATIC_O2DIV = 20; //@IPC int 2,128

localparam CLKO3_SEL = 1; //@IPC enum 0,1,2,3

localparam DYNAMIC_O3DIV_EN = "FALSE"; //@IPC bool

localparam STATIC_O3DIV = 20; //@IPC int 2,128

localparam CLKO4_SEL = 1; //@IPC enum 0,1,2,3

localparam DYNAMIC_O4DIV_EN = "FALSE"; //@IPC bool

localparam STATIC_O4DIV = 20; //@IPC int 2,128

localparam INTERNAL_FB1 = 1; //@IPC enum 0,1,2,3

localparam INTERNAL_FB_EN = "FALSE"; //@IPC bool

localparam STATIC_DU1 = 4'b1000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam STATIC_PS1 = 4'b0000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam STATIC_DU2 = 4'b1000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam STATIC_PS2 = 4'b0000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam STATIC_DU3 = 4'b1000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam STATIC_PS3 = 4'b0000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam STATIC_DU4 = 4'b1000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam STATIC_PS4 = 4'b0000; //@IPC enum 0000,0010,0100,0110,1000,1010,1100,1110

localparam CLOCK0_EN = "TRUE"; //@IPC bool

localparam CLOCK1_EN = "FALSE"; //@IPC bool

localparam CLOCK2_EN = "FALSE"; //@IPC bool

localparam CLOCK3_EN = "FALSE"; //@IPC bool

localparam CLOCK4_EN = "FALSE"; //@IPC bool

localparam GATE0_EN = "FALSE"; //@IPC bool

localparam GATE1_EN = "FALSE"; //@IPC bool

localparam GATE2_EN = "FALSE"; //@IPC bool

localparam GATE3_EN = "FALSE"; //@IPC bool

localparam GATE4_EN = "FALSE"; //@IPC bool

localparam DIV125_M = 1; //@IPC int 1,64

localparam DIV125_N = 1; //@IPC int 0,7

localparam DIV32BIT_K = 1000; //@IPC int 1,1073741823

localparam PLL_PWD_EN = "FALSE"; //@IPC bool

localparam PLL_RST_EN = "FALSE"; //@IPC bool

localparam DYNAMIC_DUPS1_EN = "FALSE"; //@IPC bool

localparam DYNAMIC_DUPS2_EN = "FALSE"; //@IPC bool

localparam DYNAMIC_DUPS3_EN = "FALSE"; //@IPC bool

localparam DYNAMIC_DUPS4_EN = "FALSE"; //@IPC bool

localparam STATIC_DU1_PS1 = 0; //@IPC enum 0,1,2,3,4,5,6,7

localparam STATIC_DU2_PS2 = 0; //@IPC enum 0,1,2,3,4,5,6,7

localparam STATIC_DU3_PS3 = 0; //@IPC enum 0,1,2,3,4,5,6,7

localparam STATIC_DU4_PS4 = 0; //@IPC enum 0,1,2,3,4,5,6,7

localparam EN_INNER_RST = "TRUE"; //@IPC bool

localparam EN_RESET_ODIV = "FALSE"; //@IPC bool

localparam EN_RESET_IDIV = "FALSE"; //@IPC bool
                      
localparam INTERNAL_FB       = (INTERNAL_FB1==0) ? "DISABLE":
                               (INTERNAL_FB1==1) ? "CLKOUT0":
                               (INTERNAL_FB1==2) ? "CLKOUT1":
                               (INTERNAL_FB1==3) ? "CLKOUT2":"DISABLE";



input           clkin1      ;

output          pll_lock    ;

output          clkout_0    ;



wire       pll_pwd            ;
wire       pll_pwd_tmp        ;
wire       pll_rst            ;
wire       pll_rst_tmp        ;
wire       clkin1             ;
wire       clkin2             ;
wire       clkin_dsel         ;
wire       clkfb              ;
wire [5:0] dyn_idiv           ;
wire [5:0] dyn_fdiv           ;
wire [5:0] dynodiv            ;
wire [5:0] dyno2div           ;
wire [5:0] dyno3div           ;
wire [5:0] dyno4div           ; 
wire [3:0] cim_dyndu1         ;
wire [3:0] cim_dyndu2         ;
wire [3:0] cim_dyndu3         ;
wire [3:0] cim_dyndu4         ;
wire [3:0] cim_dynps1         ;
wire [3:0] cim_dynps2         ;
wire [3:0] cim_dynps3         ;
wire [3:0] cim_dynps4         ;
wire [2:0] dynps1             ;
wire [2:0] dynps2             ;
wire [2:0] dynps3             ;
wire [2:0] dynps4             ;
wire       reset_idiv         ;
wire       reset_idiv_tmp     ;
wire       reset_odiv         ;
wire       reset_odiv_tmp     ;
wire       gateo_0            ;
wire       gateo_1            ;
wire       gateo_2            ;
wire       gateo_3            ;
wire       gateo_4            ;
wire       pll_lock           ;
wire       clkout_0           ;
wire       clkout_1           ;
wire       clkout_2           ;
wire       clkout_3           ;
wire       clkout_4           ;
                              
wire [4:0] gateo              ;
wire [4:0] clkout             ;

assign cim_dynps1 = {dynps1, 1'b0};
assign dynps1_msb_inv = ~dynps1[2];
assign cim_dyndu1 = {dynps1_msb_inv,dynps1[1:0], 1'b0};
assign cim_dynps2 = {dynps2, 1'b0};
assign dynps2_msb_inv = ~dynps2[2];
assign cim_dyndu2 = {dynps2_msb_inv,dynps2[1:0], 1'b0};
assign cim_dynps3 = {dynps3, 1'b0};
assign dynps3_msb_inv = ~dynps3[2];
assign cim_dyndu3 = {dynps3_msb_inv,dynps3[1:0], 1'b0};
assign cim_dynps4 = {dynps4, 1'b0};
assign dynps4_msb_inv = ~dynps4[2];
assign cim_dyndu4 = {dynps4_msb_inv,dynps4[1:0], 1'b0};




assign     pll_pwd_tmp = (PLL_PWD_EN=="TRUE") ? pll_pwd : 0; 
assign     pll_rst_tmp = (PLL_RST_EN=="TRUE") ? pll_rst : 0; 
assign     reset_idiv_tmp = (EN_RESET_IDIV=="TRUE") ? reset_idiv : 0;
assign     reset_odiv_tmp = (EN_RESET_ODIV=="TRUE") ? reset_odiv : 0; 





GTP_PLL_WRAPPER #(
.CLKIN_FREQ         (CLKIN_FREQ         ), 
.DYNAMIC_CLKIN_EN   (DYNAMIC_CLKIN_EN   ),
.CLKIN_SSEL         (CLKIN_SSEL         ),
.DYNAMIC_IDIV_EN    (DYNAMIC_IDIV_EN    ),
.STATIC_IDIV        (STATIC_IDIV        ),
.DYNAMIC_FDIV_EN    (DYNAMIC_FDIV_EN    ),
.STATIC_FDIV        (STATIC_FDIV        ),
.DYNAMIC_ODIV_EN    (DYNAMIC_ODIV_EN    ),
.STATIC_ODIV        (STATIC_ODIV        ),
.CLKO2_SEL          (CLKO2_SEL          ),
.DYNAMIC_O2DIV_EN   (DYNAMIC_O2DIV_EN   ), 
.STATIC_O2DIV       (STATIC_O2DIV       ), 
.CLKO3_SEL          (CLKO3_SEL          ), 
.DYNAMIC_O3DIV_EN   (DYNAMIC_O3DIV_EN   ), 
.STATIC_O3DIV       (STATIC_O3DIV       ),
.CLKO4_SEL          (CLKO4_SEL          ),
.DYNAMIC_O4DIV_EN   (DYNAMIC_O4DIV_EN   ),
.STATIC_O4DIV       (STATIC_O4DIV       ),
.INTERNAL_FB        (INTERNAL_FB        ),
.DYNAMIC_DUPS1_EN   (DYNAMIC_DUPS1_EN   ),
.STATIC_DU1         (STATIC_DU1         ),
.STATIC_PS1         (STATIC_PS1         ),
.DYNAMIC_DUPS2_EN   (DYNAMIC_DUPS2_EN   ),
.STATIC_DU2         (STATIC_DU2         ),
.STATIC_PS2         (STATIC_PS2         ),
.DYNAMIC_DUPS3_EN   (DYNAMIC_DUPS3_EN   ),
.STATIC_DU3         (STATIC_DU3         ),
.STATIC_PS3         (STATIC_PS3         ),
.DYNAMIC_DUPS4_EN   (DYNAMIC_DUPS4_EN   ),
.STATIC_DU4         (STATIC_DU4         ),
.STATIC_PS4         (STATIC_PS4         ),
.GATEO_EN           (GATE0_EN           ),
.GATE1_EN           (GATE1_EN           ),
.GATE2_EN           (GATE2_EN           ),
.GATE3_EN           (GATE3_EN           ),
.GATE4_EN           (GATE4_EN           ),
.DIV125_M           (DIV125_M           ),
.DIV125_N           (DIV125_N           ),
.DIV32BIT_K         (DIV32BIT_K         ),
.EN_INNER_RST       (EN_INNER_RST       ),
.EN_RESET_ODIV      (EN_RESET_ODIV      ),
.EN_RESET_IDIV      (EN_RESET_IDIV      )
) I_GTP_PLL(
.PLL_PWD         (pll_pwd_tmp     ),
.PLL_RST         (pll_rst_tmp     ),
.CLKIN1          (clkin1          ),
.CLKIN2          (clkin2          ),
.CLKIN_DSEL      (clkin_dsel      ),
.CLKFB           (clkfb           ),
.DYN_IDIV        (dyn_idiv        ),
.DYN_FDIV        (dyn_fdiv        ),
.CIM_DYNODIV     (dynodiv         ),
.CIM_DYNO2DIV    (dyno2div        ),
.CIM_DYNO3DIV    (dyno3div        ),
.CIM_DYNO4DIV    (dyno4div        ), 
.CIM_DYNDU1      (cim_dyndu1      ),
.CIM_DYNDU2      (cim_dyndu2      ),
.CIM_DYNDU3      (cim_dyndu3      ),
.CIM_DYNDU4      (cim_dyndu4      ),
.CIM_DYNPS1      (cim_dynps1      ),
.CIM_DYNPS2      (cim_dynps2      ),
.CIM_DYNPS3      (cim_dynps3      ),
.CIM_DYNPS4      (cim_dynps4      ),
.RESET_IDIV      (reset_idiv_tmp  ),
.RESET_ODIV      (reset_odiv_tmp  ),
.GATEO           (gateo           ),
.PLL_LOCK        (pll_lock        ),
.CLKOUT          (clkout          )
);

assign gateo[0] = gateo_0  ;
assign gateo[1] = gateo_1  ;
assign gateo[2] = gateo_2  ;
assign gateo[3] = gateo_3  ;
assign gateo[4] = gateo_4  ;


assign clkout_0 = clkout[0];
assign clkout_1 = clkout[1];
assign clkout_2 = clkout[2];
assign clkout_3 = clkout[3];
assign clkout_4 = clkout[4];

endmodule
